add_executable(MemoryBenchmarks MemoryBenchmarks.cpp)
target_link_libraries(MemoryBenchmarks PRIVATE Core)
target_compile_features(MemoryBenchmarks PRIVATE cxx_std_20)
set_property(TARGET MemoryBenchmarks PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
if(MSVC)
	target_compile_options(MemoryBenchmarks PRIVATE /W4 /utf-8 /GL-)
	target_compile_definitions(MemoryBenchmarks PRIVATE UNICODE _UNICODE)
else()
	target_compile_options(MemoryBenchmarks PRIVATE -Wall -Wextra -Wpedantic)
endif()
